### ISSUE TITLE
同为vim爱好者，请问可以加群交流吗？

### ISSUE THREAD

**Issue by chobijaeyu** [LintaoAmons/astronvim_user#1]
突然打扰不好意思，我在b站看了up的视频，刚好这两天也在折腾astrovim，但是b站没办法评论，请问可以加个好友一起学习交流吗？
discord，google group之类的不涉及隐私的方式就好。

**Comment by LintaoAmons** [comment]
老哥，B站可以私信啊

**Comment by chobijaeyu** [comment]
因为没有国内的手机号，不然已经发私信了。

**Comment by LintaoAmons** [comment]
原来是这样，discord没搞过啊，怎么加好友？

**Comment by chobijaeyu** [comment]
chobijaeyu#4529 这是我的discord id。你也可以创建一个服务器邀请我们，可能还有别的观众会想加进来交流吧
